### ISSUE TITLE
questionDB file cannot see

### ISSUE THREAD

**Issue by leo218744** [ivanmishev/EducationalQuizGame#1]
when I open the questionDB, I can't see the words, would you send a questionDB file using english and send it to me.

**Comment by ivanmishev** [comment]
Well i don't have version with English questions but you can create it yourself. It's simple db with this fields: {"Question", "cAnswer", "wAnswer1", "wAnswer2", "wAnswer3", "difficulty"} (in that order).
p.s. diff field is valuated from 1 to 4
